### ISSUE TITLE
how to set the initial pose? 

### ISSUE THREAD

**Issue by ibrahimhroob** [robotics-upo/dll#12]
Hi @fercabe 

when I launch the node with the default parameters, I got the initial pose wrong, what are the correct values? please see the attached photo and here the launch file:
https://github.com/robotics-upo/dll/blob/dee70aad89737544d67e154fb39d4b6b09717c2a/launch/airsim1.launch

![rviz_screenshot_2023_04_25-18_41_05](https://user-images.githubusercontent.com/47870260/234358642-a83b0709-f62e-4d0f-99dc-a9a2cd2f685f.png)

**Comment by fercabe** [comment]
Hi Ibrahim,

You must set the parameters initial_x, initial_y, initial_z and initial_a (yaw angle) in the launch file. Don't know why the initial point is no longer working, probably due to latest updates of the code. 

To get the initial position: go to rviz, click on "2D pose estimate" and then click in the map in the position where you think the robot is. Then, go to the terminal from with you launched the rviz, you will be able to see the 2D position and orientation of the clicked point. Use it to set the initial_? variables in the launch file.

I will try to properly setup the initial position in the launch files as soon as possible, and update the repo.

Regards,
Fernando Caballero

**Comment by ibrahimhroob** [comment]
Thanks for your reply 🙏

**Comment by homocysteine** [comment]
I meet the same problem in airsim1, too. Have you found the correct initial position? @ibrahimhroob

**Comment by fercabe** [comment]
Hi, 

I just updated the airsmin launch files with the correct initial position. It was changed after some software updates in the grid map proccessing, but forgot to update the launch files. Please, update your repo and check it works.

Very important, remember you need an odometry. In the paper we used LOAM as lidar odometer. The launch file creates a FAKE odometry (just zero) that makes the localization diverge after some iterations.
