### ISSUE TITLE
tested the given bag failed

### ISSUE THREAD

**Issue by numb0824** [robotics-upo/dll#2]
Hi,
     thanks for your great work!
     I have download the given bag for test the dll,but when i launched the launch file,it always shows the error,which is :
"
Octomap loaded
Map size:
	x: 37.2 to 92.75
	y: 41.95 to 95.65
	z: -10.4 to 0.15
	Res: 0.05
Error opening file /home/whx/study/dll_ws/src/dll/maps/airsim.grid for reading
Computing 3D occupancy grid. This will take some time...
[ INFO] [1640669470.668451692, 1614448809.604375476]: Progress: 0.000000 %
[ INFO] [1640669471.163893210, 1614448810.107720910]: Progress: 0.021567 %
[ INFO] [1640669471.668560708, 1614448810.612384198]: Progress: 0.039648 %
[ INFO] [1640669472.172075265, 1614448811.115887848]: Progress: 0.053874 %
[ INFO] [1640669472.680451449, 1614448811.624293216]: Progress: 0.065055 %
[ INFO] [1640669473.184041975, 1614448812.127884273]: Progress: 0.073926 %
...
...
[bag_player-2] process has finished cleanly
log file: /home/whx/.ros/log/5879e12a-679f-11ec-9f57-c0e43482dfff/bag_player-2*.log
"
I have noticed there is a closed issue which talk about it,so i repeated the same test for many times.But it didn't work.

I hope someone can help me solve the problem.

Best wishes

**Comment by fercabe** [comment]
Hi,

There is actually no error. The problem is that the bag finished before the grid map is computed, but the "Progress: X.XXXXX %" message was displayed using a ROS_INFO_THROTTLE, which stop displaying when the rosbag play stops.

I just commited some small changes to provide more comprehensive information when the .grid file is not found. Now, when the .grid file is not found, the following information will be displayed:

_/path/to/grid/file.grid not found!
Computing 3D occupancy grid. This will take some time...
Computing grid map: **X.XXXXX%**        
Grid map successfully saved on /path/to/grid/file.grid_

You should see how the **X.XXXX** values goes from 0.0 to 100. This will take time for large maps as the Airsim one, but only must be done once per map. Once the grid is created and saved you will need to re-launch the launch file because the rosbag play was most probably ended.

Please, update your code and check that everithing works.

Regards,
Fernando Caballero

**Comment by numb0824** [comment]
> 

Dear fercabe:
  I am very grateful to you for taking the time to solve my questions. I will try it.
  Thanks a lot
