### ISSUE TITLE
How to run other datasets like KITTI？

### ISSUE THREAD

**Issue by MIke-1118** [robotics-upo/dll#7]
I want to run other datasets like KITTI to test the program. How can i do? Thanks!

**Comment by MartinEekGerhardsen** [comment]
I'm not too familiar with KITTI, however the gist of using the package with other datasets is to ensure that you get some way of expressing the data in `ros` (you don't have to use a `rosbag` like in the examples), so you'll need the lidar data on some topic, preferably some IMU data, a prior map in the .bt format and an initial position within this prior map. 

Note that the maps cannot include negative points! As an example, I tried this method with a map where the robot was in the origin, which was in the middle of a room. I thought I should then have the initial position (0, 0, 0), however because the smallest value in x was -3, in y was -2.5 and in z was 0 the actual initial position was (3, 2.5, 0), because the prior map is shifted when loaded into the package. So keep that in mind if you use your own map.

**Comment by MIke-1118** [comment]
Thank you so much. You've helped me so much. Thanks！

**Comment by MartinEekGerhardsen** [comment]
No problem :slightly_smiling_face:

**Comment by MIke-1118** [comment]
What does the “an initial position within this prior map” mean？ The pose of the robot when drawing the map？

**Comment by MartinEekGerhardsen** [comment]
Essentially where your robot starts relative the map you use. Basically you need to give the method a _close enough_ position of the robots relative to the map. 

E.g. in this 2D map, the initial position of the robot R is (3, 2)
```
^
|
y|
 |
5|
4|
3|
2|     R
1|
-|---------------
0| 1 2 3 4 5 x ->
```

**Comment by fercabe** [comment]
Hi guys,

@MartinEekGerhardsen, thanks very much for the detailed answer. Fully agree with this.

Just to remark that DLL is a LIDAR-based localization approach, not an odometry neither a SLAM method. KITTI dataset is mostly oriented for odometry benchmarking, but not for localization.

Also, @MIke-1118, please take a careful reading of the paper associated to this source code. You can find the paper in ArXiv for free. 

I close this issue
Fernando
